apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-users-api
  labels:
    app: fcg-users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-users-api
  template:
    metadata:
      labels:
        app: fcg-users-api
    spec:
      imagePullSecrets:
        - name: fcg-acr-secret
      containers:
        - name: fcg-users-api
          image: ${DOCKER_REGISTRY}/fcg-users-api:${DOCKER_IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: fcg-users-api-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
